version: '3'

services:
  db:
    container_name: postgres_database
    image: postgres:15.1
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:   # ← corregido: antes decía "enviroment"
      - POSTGRES_PASSWORD=123456  # ← corregido: era "POSTGRESS_PASSWORD"

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:6.17  # ← corregido: antes era "pgasmin4"
    ports:
      - "8080:80"
    environment:   # ← corregido
      - PGADMIN_DEFAULT_PASSWORD=123456
      - PGADMIN_DEFAULT_EMAIL=superman@google.com

volumes:
  postgres-db:
